from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from common import (
    AUDIT_DIR,
    STATUS_FILE,
    PhaseStatus,
    ToolchainConfig,
    dependency_map,
    fatal_status,
    file_exists_within,
    finalize,
    make_failure_status,
    read_json,
    read_text_file,
    resolve_toolchain,
    run_cmd,
    safe_repo_relative_path,
    set_audit_dir,
    strip_solidity_comments,
    which,
    write_text,
)


# ── FAMILY_ASSERTIONS import from exploit-templates ──────────────────────────────
try:
    _et_base = Path(__file__).resolve().parent.parent / "cerberus-exploit-templates" / "resources"
    if str(_et_base.parent) not in __import__("sys").path:
        import sys as _sys
        _sys.path.insert(0, str(_et_base.parent))
    from exploit_templates import FAMILY_ASSERTIONS
except Exception:
    FAMILY_ASSERTIONS = {}  # type: ignore[assignment, misc]


EXPLOIT_TEMPLATE = """// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
{base_import}import "{contract_path}";

contract {contract_name}ExploitPoC is {base_contract} {{
    {contract_name} internal target;
    address internal attacker = makeAddr("attacker");

    function setUp() public virtual override {{
{base_setup}        // Audit context:
{contest_lines}{privilege_lines}{invariant_lines}{violated_invariant_lines}{blocking_assumptions_lines}{rule_lines}{exploit_lines}{proof_plan_lines}{role_lines}{setter_lines}{sink_lines}
        // TODO(agent): replace this with the real deployment/setup path.
        // Prefer the repo's existing harness over ad hoc deployment when available.
        // Example:
        // target = {contract_name}(deployedAddress);
        revert("TODO: implement protocol-specific setup");
    }}

    function test_Exploit() public {{
        vm.startPrank(attacker);

{exploit_body_stub}        vm.stopPrank();
    }}
}}
"""


INVARIANT_TEMPLATE = """// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
{base_import}import "{contract_path}";

contract {contract_name}Handler is {base_contract} {{
    {contract_name} internal target;

    constructor({contract_name} _target) {{
        target = _target;
    }}

{invariant_lines}{violated_invariant_lines}
    // TODO(agent): add bounded wrapper calls that mutate the protocol state.
}}

contract {contract_name}InvariantTest is {base_contract} {{
    {contract_name} internal target;
    {contract_name}Handler internal handler;

    function setUp() public virtual override {{
{base_setup}        // TODO(agent): wire the real target into the handler and register invariants.
        revert("TODO: implement protocol-specific setup");
    }}

    // TODO(agent): add invariant checks that fail on role/state drift or accounting breaks.
}}
"""


HARDHAT_EXPLOIT_TEMPLATE = """// SPDX-License-Identifier: UNLICENSED
// Scaffolding generated by cerberus-proof-auditor for Hardhat projects.
// Replace TODO markers with compile-ready exploit logic.

import {{ ethers, network }} from "hardhat";
import {{ expect }} from "chai";

// Audit context:
{contest_lines}{privilege_lines}{invariant_lines}{violated_invariant_lines}{blocking_assumptions_lines}{rule_lines}{exploit_lines}{proof_plan_lines}{role_lines}{setter_lines}{sink_lines}

describe("{contract_name} Exploit PoC", function () {{
  this.timeout(120_000);

{exploit_body_stub}  it("TODO: implement exploit PoC", async function () {{
    // Example structure:
    // const [deployer, attacker] = await ethers.getSigners();
    // const Contract = await ethers.getContractFactory("{contract_name}");
    // const contract = await Contract.deploy(...);
    // await contract.deployed();
    // TODO: execute exploit
    expect.fail("TODO: implement");
  }});
}});
"""


HARDHAT_INVARIANT_TEMPLATE = """// SPDX-License-Identifier: UNLICENSED
// Scaffolding generated by cerberus-proof-auditor for Hardhat projects.
// Replace TODO markers with compile-ready invariant tests.

import {{ hre }} from "hardhat";

// Audit context:
{contest_lines}{privilege_lines}{invariant_lines}{violated_invariant_lines}{blocking_assumptions_lines}{rule_lines}{exploit_lines}{proof_plan_lines}{role_lines}{setter_lines}{sink_lines}

describe("{contract_name} Invariant Tests", function () {{
  this.timeout(300_000);

  // TODO(agent): define invariant properties that should hold across all state transitions.
  // Example: assert no role drift, no callback state corruption, no accounting breaks.

  it("TODO: implement invariant test", async function () {{
    // TODO: wire handlers and run invariant testing
    // Recommended: use hardhat-invariant plugin or implement custom handler-based approach
    expect.fail("TODO: implement");
  }});
}});
"""


GENERIC_EXPLOIT_TEMPLATE = """// SPDX-License-Identifier: UNLICENSED
// Generic test stub — no Foundry or Hardhat dependency required.
// Implement test logic using assert() or revert() directly.
// Compile with: solc --bin test/{contract_name}Exploit.test.sol

// Audit context:
{contest_lines}{privilege_lines}{invariant_lines}{violated_invariant_lines}{blocking_assumptions_lines}{rule_lines}{exploit_lines}{proof_plan_lines}{role_lines}{setter_lines}{sink_lines}

contract {contract_name}ExploitTest {{
{exploit_body_stub}    // TODO(agent): implement setup and exploit logic.
    // Use assert() for positive checks and revert() for negative checks.
    //
    // Example structure:
    // function testExploit() public {{
    //     // Deploy {contract_name}
    //     // Seed privileged/user state
    //     // Execute exploit path
    //     // Assert the violated invariant or attacker profit
    //     assert(false, "{violated_invariant_placeholder}");
    // }}
}}
"""


GENERIC_INVARIANT_TEMPLATE = """// SPDX-License-Identifier: UNLICENSED
// Generic invariant test stub — no Foundry or Hardhat dependency required.
// Compile with: solc --bin test/{contract_name}Invariant.test.sol

// Audit context:
{contest_lines}{privilege_lines}{invariant_lines}{violated_invariant_lines}{rule_lines}{exploit_lines}{proof_plan_lines}{role_lines}{setter_lines}{sink_lines}

contract {contract_name}InvariantTest {{
    // TODO(agent): implement invariant properties that should hold across all state mutations.
    //
    // Example:
    // function invariantNoRoleDrift() public {{
    //     // Assert that: {violated_invariant_placeholder}
    //     assert(false, "{violated_invariant_placeholder}");
    // }}
}}
"""


def _count_remaining_todos(path: Path) -> int:
    """Return the count of unresolved TODO/PLACEHOLDER markers in a file."""
    if not path.exists():
        return 0
    content = path.read_text(encoding="utf-8", errors="ignore")
    pattern = re.compile(r"TODO|PLACEHOLDER|FIXME|XXX", re.IGNORECASE)
    return len(pattern.findall(content))


def _load_vector_knowledge(contract_name: str, contract_path: str) -> Dict[str, Any]:
    """Load vector candidates and extract knowledge for knowledge-grounded scaffolding."""
    vectors_raw = read_json(AUDIT_DIR / "vector_candidates.json")
    vectors = vectors_raw.get("vectors", []) if isinstance(vectors_raw, dict) else []

    matched_vectors: List[Dict[str, Any]] = []
    for v in vectors:
        if not isinstance(v, dict):
            continue
        seq = v.get("transaction_sequence", [])
        # Match vectors that reference this contract
        if any(str(contract_name).lower() in str(step.get("contract", "")).lower() for step in seq):
            matched_vectors.append(v)
        elif any(str(contract_path).lower() in str(step.get("contract", "")).lower() for step in seq):
            matched_vectors.append(v)
        # Also match by family if no sequence match
        elif not seq and str(contract_name).lower() in str(v.get("title", "")).lower():
            matched_vectors.append(v)

    # Sort by confidence descending, take the best one
    matched_vectors.sort(key=lambda v: float(v.get("confidence", 0.0)), reverse=True)
    best_vector = matched_vectors[0] if matched_vectors else {}

    return best_vector


def _render_assertion_stub(assertion_templates: List[Any], vector_seq: List[Dict[str, Any]], indent: str = "        ") -> str:
    """Render concrete assertion stubs from FAMILY_ASSERTIONS + vector sequence.

    Each assertion is rendered with the step's function name and precondition
    substituted in, replacing generic placeholders.
    """
    if not assertion_templates and not vector_seq:
        return ""

    lines: List[str] = []
    if assertion_templates:
        for at in assertion_templates[:3]:
            # Extract step number from assertion step field
            step_hint = str(getattr(at, "step", "")).strip()
            rendered_assertion = getattr(at, "assertion", "")
            rationale = getattr(at, "rationale", "")

            # Try to match to a sequence step
            matched_step: Optional[Dict[str, Any]] = None
            if step_hint in ("post_exploit", "final", "invariant_check"):
                matched_step = vector_seq[-1] if vector_seq else None
            elif step_hint in ("pre_exploit", "start"):
                matched_step = vector_seq[0] if vector_seq else None

            fn_name = ""
            if matched_step:
                fn_name = str(matched_step.get("function", "")).strip()

            # Build the concrete assertion
            assertion_text = rendered_assertion
            if fn_name and "<fn>" in assertion_text:
                assertion_text = assertion_text.replace("<fn>", fn_name)

            if assertion_text:
                lines.append(f"{indent}// {rationale}")
                lines.append(f"{indent}{assertion_text}")
                lines.append(f"{indent}// (replace with compile-ready assertion)")
                lines.append("")
    else:
        # Fallback: generate stubs from vector sequence
        for i, step in enumerate(vector_seq[:3], 1):
            fn = str(step.get("function", "")).strip()
            precondition = str(step.get("precondition", "")).strip()
            expected_revert = step.get("expected_revert", False)
            if expected_revert:
                lines.append(f"{indent}// Step {i} ({fn}): expect revert — {precondition}")
                lines.append(f"{indent}vm.expectRevert(); // {fn}()")
                lines.append("")
            else:
                lines.append(f"{indent}// Step {i} ({fn}): {precondition}")
                lines.append(f"{indent}// assert correctness of {fn}()")
                lines.append("")

    return "".join(lines)


def _render_exploit_body_stub(
    vector: Dict[str, Any],
    family_assertions: List[Any],
    contract_name: str,
    indent: str = "        ",
) -> str:
    """Render a knowledge-grounded exploit body from vector data and family assertions."""
    seq = vector.get("transaction_sequence", []) if isinstance(vector, dict) else []
    family = str(vector.get("family", "")) if isinstance(vector, dict) else ""

    lines: List[str] = []
    lines.append(f"{indent}// Knowledge-grounded exploit body for {family}:")
    lines.append("")

    if seq:
        for i, step in enumerate(seq, 1):
            fn = str(step.get("function", "")).strip()
            actor = str(step.get("actor", "attacker")).strip()
            contract = str(step.get("contract", contract_name)).strip()
            params = step.get("parameters", {}) if isinstance(step, dict) else {}
            precondition = str(step.get("precondition", "")).strip()
            expected_revert = step.get("expected_revert", False)

            if fn.startswith("<") or not fn:
                lines.append(f"{indent}// Step {i}: {precondition}")
                lines.append(f"{indent}// TODO: implement step {i}")
                lines.append("")
                continue

            lines.append(f"{indent}// Step {i}: {actor}.{contract}.{fn}()")
            lines.append(f"{indent}// Precondition: {precondition}")
            if expected_revert:
                lines.append(f"{indent}vm.expectRevert(); // step {i} — {fn}() should revert")
            if actor == "attacker":
                lines.append(f"{indent}vm.prank(attacker); // step {i}")
            param_str = ", ".join(f"{k}={v}" for k, v in params.items()) if params else ""
            lines.append(f"{indent}target.{fn}({param_str});")
            lines.append("")
    else:
        lines.append(f"{indent}// No transaction sequence available for {family}.")
        lines.append(f"{indent}// TODO: implement exploit based on {family} pattern")
        lines.append("")

    # Append family-specific assertion stubs
    if family_assertions:
        lines.append(f"{indent}// ── Assertion stubs from {family} template ──")
        lines.append(_render_assertion_stub(family_assertions, seq, indent))
    else:
        lines.append(f"{indent}// ── Generic assertion stubs ──")
        lines.append(_render_assertion_stub([], seq, indent))

    return "".join(lines)


_SOLIDITY_RESERVED = frozenset({
    "address", "bool", "bytes", "contract", "enum", "event", "function",
    "interface", "library", "mapping", "memory", "modifier", "payable",
    "public", "private", "internal", "external", "pure", "view", "returns",
    "storage", "struct", "tuple", "type", "uint", "int", "string",
    "assembly", "break", "case", "catch", "continue", "default", "delete",
    "do", "else", "emit", "error", "fallback", "for", "if", "import",
    "indexed", "new", "override", "pragma", "receive", "revert", "return",
    "super", "this", "throw", "try", "unchecked", "using", "virtual",
    "while",
})


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scaffold Foundry exploit and invariant tests.")
    parser.add_argument(
        "--target-dir",
        default=".",
        help="Directory containing the Solidity project. Defaults to CWD.",
    )
    parser.add_argument("--contract-name", required=True, help="Target contract name.")
    parser.add_argument("--contract-path", required=True, help="Repo-relative path to the contract .sol file.")
    parser.add_argument(
        "--output-dir",
        default="test/root-audit",
        help="Directory for generated tests. Defaults to test/root-audit.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite previously scaffolded test files if they already exist.",
    )
    return parser.parse_args()


def build_paths(contract_name: str, output_dir: str, scaffold_family: str = "foundry") -> tuple[Path, Path]:
    test_dir = Path(output_dir)
    if scaffold_family == "hardhat":
        exploit_path = test_dir / f"{contract_name}ExploitPoC.test.ts"
        invariant_path = test_dir / f"{contract_name}InvariantTest.test.ts"
    elif scaffold_family == "generic":
        exploit_path = test_dir / f"{contract_name}Exploit.test.sol"
        invariant_path = test_dir / f"{contract_name}Invariant.test.sol"
    else:
        # foundry
        exploit_path = test_dir / f"{contract_name}ExploitPoC.t.sol"
        invariant_path = test_dir / f"{contract_name}InvariantTest.t.sol"
    return exploit_path, invariant_path


def format_comment_block(prefix: str, lines: List[str]) -> str:
    if not lines:
        return f"        // {prefix}: not determined\n"
    rendered = [f"        // {prefix}: {lines[0]}"]
    rendered.extend(f"        // {line}" for line in lines[1:])
    return "\n".join(rendered) + "\n"


def prioritize_candidates(candidates: List[str], context_lines: List[str]) -> List[str]:
    seen: List[str] = []
    for line in context_lines:
        match = re.search(r"::([A-Za-z_][A-Za-z0-9_]*)", line)
        if match:
            name = match.group(1)
            if name in candidates and name not in seen:
                seen.append(name)
    for candidate in candidates:
        if candidate not in seen:
            seen.append(candidate)
    return seen


def load_context_lines(contract_name: str, contract_path: str) -> Dict[str, List[str]]:
    contest_lines: List[str] = []
    privilege_lines: List[str] = []
    invariant_lines: List[str] = []
    rule_lines: List[str] = []
    exploit_lines: List[str] = []
    role_lines: List[str] = []
    setter_lines: List[str] = []
    sink_lines: List[str] = []
    proof_plan_lines: List[str] = []

    contest_context = read_json(AUDIT_DIR / "contest_context.json")
    if contest_context:
        if contest_context.get("scope_files"):
            contest_lines.append(f"in-scope files: {len(contest_context['scope_files'])}")
        if contest_context.get("known_issues"):
            contest_lines.append(f"known/public issues listed: {len(contest_context['known_issues'])}")
        notes = contest_context.get("contest_notes", {})
        if isinstance(notes, dict):
            contest_lines.extend(str(value) for value in notes.values())

    privilege_map = (AUDIT_DIR / "privilege_map.md").read_text(encoding="utf-8", errors="ignore") if (AUDIT_DIR / "privilege_map.md").exists() else ""
    target_file_hint = contract_path
    target_contract_hint = f"::{contract_name}"
    fallback_privilege: List[str] = []
    for line in privilege_map.splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            entry = stripped[2:]
            if target_file_hint in entry or target_contract_hint in entry:
                privilege_lines.append(entry)
            else:
                fallback_privilege.append(entry)
        if len(privilege_lines) >= 4:
            break
    if len(privilege_lines) < 4:
        privilege_lines.extend(fallback_privilege[: 4 - len(privilege_lines)])

    invariant_map = (AUDIT_DIR / "invariant_map.md").read_text(encoding="utf-8", errors="ignore") if (AUDIT_DIR / "invariant_map.md").exists() else ""
    fallback_invariant: List[str] = []
    for line in invariant_map.splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            entry = stripped[2:]
            if target_file_hint in entry or target_contract_hint in entry:
                invariant_lines.append(entry)
            else:
                fallback_invariant.append(entry)
        if len(invariant_lines) >= 4:
            break
    if len(invariant_lines) < 4:
        invariant_lines.extend(fallback_invariant[: 4 - len(invariant_lines)])

    rule_scan = read_json(AUDIT_DIR / "rule_scan.json")
    for item in rule_scan.get("findings", []) if isinstance(rule_scan, dict) else []:
        if not isinstance(item, dict):
            continue
        if contract_path in str(item.get("path", "")):
            rule_lines.append(f"{item.get('rule_id')}: {item.get('message')}")
        if len(rule_lines) >= 4:
            break

    exploit_rankings = (AUDIT_DIR / "exploit_rankings.md").read_text(encoding="utf-8", errors="ignore") if (AUDIT_DIR / "exploit_rankings.md").exists() else ""
    for line in exploit_rankings.splitlines():
        stripped = line.strip()
        if stripped.startswith("- ") and (contract_path in stripped or contract_name in stripped):
            exploit_lines.append(stripped[2:])
        if len(exploit_lines) >= 4:
            break

    proof_plans = read_json(AUDIT_DIR / "proof_plans.json")
    for item in proof_plans.get("proof_plans", []) if isinstance(proof_plans, dict) else []:
        if not isinstance(item, dict):
            continue
        preferred = str(item.get("preferred_test_path", ""))
        sequence = item.get("transaction_sequence", [])
        assertions = item.get("assertions", [])
        if contract_path in preferred or contract_name in str(item.get("title", "")):
            if isinstance(sequence, list):
                proof_plan_lines.extend(str(entry) for entry in sequence[:2])
            if isinstance(assertions, list):
                proof_plan_lines.extend(f"assert: {entry}" for entry in assertions[:2])
        if len(proof_plan_lines) >= 4:
            break

    contract_source = read_text_file(Path(contract_path))
    code_only = strip_solidity_comments(contract_source)
    role_lines.extend(dict.fromkeys(re.findall(r"\b([A-Z][A-Z0-9_]*_ROLE)\b", code_only)))

    functions = re.findall(r"\bfunction\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", code_only)
    setter_keywords = ("set", "update", "configure", "change", "grant", "revoke")
    sink_keywords = ("withdraw", "rescue", "claim", "mint", "burn", "transfer", "sweep", "collect", "execute")
    setter_candidates = list(dict.fromkeys(name for name in functions if name.lower().startswith(setter_keywords)))
    sink_candidates = list(dict.fromkeys(name for name in functions if any(keyword in name.lower() for keyword in sink_keywords)))
    prioritized_context = privilege_lines + invariant_lines
    setter_lines.extend(prioritize_candidates(setter_candidates, prioritized_context))
    sink_lines.extend(prioritize_candidates(sink_candidates, prioritized_context))

    return {
        "contest": contest_lines[:4],
        "privilege": privilege_lines[:4],
        "invariant": invariant_lines[:4],
        "rules": rule_lines[:4],
        "exploits": exploit_lines[:4],
        "proof_plans": proof_plan_lines[:4],
        "roles": role_lines[:4],
        "setters": setter_lines[:4],
        "sinks": sink_lines[:4],
        # Rich finding-candidate fields for knowledge-grounded stub comments
        "violated_invariant": _load_violated_invariant(contract_path),
        "blocking_assumptions": _load_blocking_assumptions(contract_path),
    }


def _load_violated_invariant(contract_path: str) -> List[str]:
    """Extract violated_invariant from the best matching finding candidate."""
    candidates = read_json(AUDIT_DIR / "finding_candidates.json")
    best: Dict[str, Any] = {}
    best_score = -1.0
    for fc in candidates.get("findings", []) if isinstance(candidates, dict) else []:
        if not isinstance(fc, dict):
            continue
        if contract_path in str(fc.get("target_contract", "")):
            score = float(fc.get("confidence_score", 0.0))
            if score > best_score:
                best_score = score
                best = fc
    invariant = str(best.get("violated_invariant", "")).strip()
    return [invariant] if invariant else []


def _load_blocking_assumptions(contract_path: str) -> List[str]:
    """Extract blocking_unknowns (treated as blocking_assumptions) from the best matching finding candidate."""
    candidates = read_json(AUDIT_DIR / "finding_candidates.json")
    best: Dict[str, Any] = {}
    best_score = -1.0
    for fc in candidates.get("findings", []) if isinstance(candidates, dict) else []:
        if not isinstance(fc, dict):
            continue
        if contract_path in str(fc.get("target_contract", "")):
            score = float(fc.get("confidence_score", 0.0))
            if score > best_score:
                best_score = score
                best = fc
    blockers = best.get("blocking_unknowns", [])
    if isinstance(blockers, list):
        return [str(b) for b in blockers[:4] if str(b).strip()]
    return []


def existing_base_harness_import() -> tuple[str, str, str]:
    base_test = Path("test/Base.t.sol")
    if base_test.exists():
        return (
            'import {BaseTest} from "test/Base.t.sol";\n',
            "BaseTest",
            "        super.setUp();\n",
        )
    return ("", "Test", "")


def detect_scaffold_family() -> str:
    """Detect the preferred scaffold family from init phase details."""
    status_snapshot = read_json(STATUS_FILE)
    init_details = status_snapshot.get("init", {}).get("details", {}) if isinstance(status_snapshot, dict) else {}
    toolchain = init_details.get("toolchain_config") or {}
    if isinstance(toolchain, dict):
        family = toolchain.get("test_scaffold_family", "generic")
        if family:
            return str(family)
    # Fallback: resolve from filesystem
    tc = resolve_toolchain(Path(".").resolve())
    return tc.test_scaffold_family


def run_compile_check_generic(
    exploit_path: Path,
    scaffold_family: str,
    hardhat_bin: Optional[str] = None,
) -> tuple[bool, List[str]]:
    """
    Run a compile/syntax check for non-Foundry scaffold families.

    - foundry: uses forge test --match-path (existing behavior)
    - hardhat: runs hardhat compile
    - generic: uses solc --ast-compact-json for a basic syntax check
    """
    if scaffold_family == "foundry":
        return run_compile_check(exploit_path, Path("unused"))

    warnings: List[str] = []

    if scaffold_family == "hardhat":
        if not hardhat_bin:
            hardhat_bin = which("hardhat")
        if not hardhat_bin:
            return False, ["hardhat not available for scaffold compile check."]
        result = run_cmd([hardhat_bin, "compile"], cwd=Path("."), timeout=300)
        if result.ok:
            return True, []
        return False, [f"hardhat compile: {result.stderr[:300]}"]

    # Generic: basic solc syntax check
    solc_bin = which("solc")
    if not solc_bin:
        return False, ["no Solidity compiler found for syntax check."]
    # Try to parse the file as valid Solidity
    result = run_cmd([solc_bin, "--base-path", ".", str(exploit_path)], cwd=Path("."), timeout=60)
    if result.returncode == 0:
        return True, []
    # solc returns non-zero for warnings too — check stderr for actual errors
    stderr = result.stderr.strip()
    if not stderr:
        return True, []  # No output = no errors
    # Only fail on parse errors, not on unused variables etc.
    if "ParserError" in stderr or "SyntaxError" in stderr or "Error:" in stderr.split("\n")[0]:
        return False, [f"solc syntax error: {stderr[:300]}"]
    return True, [f"solc warnings (non-blocking): {stderr[:200]}"]


def run_compile_check(exploit_path: Path, invariant_path: Path) -> tuple[bool, List[str]]:
    forge_bin = dependency_map("forge").get("forge")
    if not forge_bin:
        return False, ["forge not available for scaffold compile check."]

    warnings: List[str] = []
    for path in (exploit_path, invariant_path):
        result = run_cmd(
            [forge_bin, "test", "--match-path", str(path), "--match-test", "^$"],
            cwd=Path("."),
            timeout=300,
        )
        if not result.ok:
            detail = result.stderr.strip() or result.stdout.strip() or f"compile check failed for {path}"
            warnings.append(detail[:280])
            return False, warnings
    return True, warnings


def main() -> int:
    args = parse_args()
    set_audit_dir(Path(args.target_dir))
    warnings: List[str] = []
    errors: List[str] = []

    try:
        status_snapshot = read_json(STATUS_FILE)
        init_details = status_snapshot.get("init", {}).get("details", {}) if isinstance(status_snapshot, dict) else {}
        run_id = init_details.get("run_id")
        contract_path = safe_repo_relative_path(args.contract_path)

        if not args.contract_name.isidentifier() or not args.contract_name[0].isupper():
            status = make_failure_status(
                "scaffold_tests",
                errors=[
                    f"Invalid Solidity contract name: '{args.contract_name}'. Must be a valid identifier starting with an uppercase letter."
                ],
                warnings=warnings,
                details={"contract_name": args.contract_name, "run_id": run_id},
            )
            return finalize(status)
        if args.contract_name.lower() in _SOLIDITY_RESERVED:
            status = make_failure_status(
                "scaffold_tests",
                errors=[f"Contract name is a Solidity reserved word: {args.contract_name}"],
                warnings=warnings,
                details={"contract_name": args.contract_name, "run_id": run_id},
            )
            return finalize(status)
        if not file_exists_within(Path("."), contract_path):
            status = make_failure_status(
                "scaffold_tests",
                errors=[f"Contract file does not exist relative to the current repo: {contract_path}"],
                warnings=warnings,
                details={"contract_name": args.contract_name, "contract_path": contract_path, "run_id": run_id},
            )
            return finalize(status)

        scaffold_family = detect_scaffold_family()
        exploit_path, invariant_path = build_paths(args.contract_name, args.output_dir, scaffold_family)
        for path in (exploit_path, invariant_path):
            if path.exists() and not args.force:
                status = make_failure_status(
                    "scaffold_tests",
                    errors=[f"Refusing to overwrite existing scaffold: {path}. Re-run with --force if replacement is intended."],
                    warnings=warnings,
                    artifacts={"exploit_test": str(exploit_path), "invariant_test": str(invariant_path)},
                    details={"contract_name": args.contract_name, "contract_path": contract_path, "run_id": run_id, "scaffold_family": scaffold_family},
                )
                return finalize(status)

        context_lines = load_context_lines(args.contract_name, contract_path)
        base_import, base_contract, base_setup = existing_base_harness_import()

        # Load vector knowledge for knowledge-grounded stubs
        vector_knowledge = _load_vector_knowledge(args.contract_name, contract_path)
        vector_family = str(vector_knowledge.get("family", "")) if vector_knowledge else ""
        family_assertions: List[Any] = []
        if vector_family and vector_family in FAMILY_ASSERTIONS:
            family_assertions = FAMILY_ASSERTIONS[vector_family]
        exploit_body_stub = _render_exploit_body_stub(vector_knowledge, family_assertions, args.contract_name)

        def audit_context() -> str:
            return "".join([
                format_comment_block("contest", context_lines["contest"]),
                format_comment_block("privilege", context_lines["privilege"]),
                format_comment_block("invariant", context_lines["invariant"]),
                format_comment_block("violated invariant", context_lines["violated_invariant"]),
                format_comment_block("blocking assumptions", context_lines["blocking_assumptions"]),
                format_comment_block("rules", context_lines["rules"]),
                format_comment_block("exploit families", context_lines["exploits"]),
                format_comment_block("proof plan", context_lines["proof_plans"]),
                format_comment_block("role constants", context_lines["roles"]),
                format_comment_block("candidate setters", context_lines["setters"]),
                format_comment_block("candidate sinks", context_lines["sinks"]),
            ])

        if scaffold_family == "hardhat":
            contest = format_comment_block("contest", context_lines["contest"])
            privilege = format_comment_block("privilege", context_lines["privilege"])
            invariant = format_comment_block("invariant", context_lines["invariant"])
            rules = format_comment_block("rules", context_lines["rules"])
            exploits = format_comment_block("exploit families", context_lines["exploits"])
            proof_plans = format_comment_block("proof plan", context_lines["proof_plans"])
            roles = format_comment_block("role constants", context_lines["roles"])
            setters = format_comment_block("candidate setters", context_lines["setters"])
            sinks = format_comment_block("candidate sinks", context_lines["sinks"])
            violated_invariant_lines = format_comment_block("violated invariant", context_lines["violated_invariant"])
            blocking_assumptions_lines = format_comment_block("blocking assumptions", context_lines["blocking_assumptions"])
            exploit_body = HARDHAT_EXPLOIT_TEMPLATE.format(
                contract_name=args.contract_name,
                contest_lines=contest,
                privilege_lines=privilege,
                invariant_lines=invariant,
                violated_invariant_lines=violated_invariant_lines,
                blocking_assumptions_lines=blocking_assumptions_lines,
                rule_lines=rules,
                exploit_lines=exploits,
                proof_plan_lines=proof_plans,
                role_lines=roles,
                setter_lines=setters,
                sink_lines=sinks,
                exploit_body_stub=exploit_body_stub,
            )
            invariant_body = HARDHAT_INVARIANT_TEMPLATE.format(
                contract_name=args.contract_name,
                contest_lines=contest,
                privilege_lines=privilege,
                invariant_lines=invariant,
                violated_invariant_lines=violated_invariant_lines,
                blocking_assumptions_lines=blocking_assumptions_lines,
                rule_lines=rules,
                exploit_lines=exploits,
                proof_plan_lines=proof_plans,
                role_lines=roles,
                setter_lines=setters,
                sink_lines=sinks,
            )
        elif scaffold_family == "generic":
            contest = format_comment_block("contest", context_lines["contest"])
            privilege = format_comment_block("privilege", context_lines["privilege"])
            invariant = format_comment_block("invariant", context_lines["invariant"])
            rules = format_comment_block("rules", context_lines["rules"])
            exploits = format_comment_block("exploit families", context_lines["exploits"])
            proof_plans = format_comment_block("proof plan", context_lines["proof_plans"])
            roles = format_comment_block("role constants", context_lines["roles"])
            setters = format_comment_block("candidate setters", context_lines["setters"])
            sinks = format_comment_block("candidate sinks", context_lines["sinks"])
            violated_invariant_lines = format_comment_block("violated invariant", context_lines["violated_invariant"])
            blocking_assumptions_lines = format_comment_block("blocking assumptions", context_lines["blocking_assumptions"])
            exploit_body = GENERIC_EXPLOIT_TEMPLATE.format(
                contract_name=args.contract_name,
                contest_lines=contest,
                privilege_lines=privilege,
                invariant_lines=invariant,
                violated_invariant_lines=violated_invariant_lines,
                blocking_assumptions_lines=blocking_assumptions_lines,
                violated_invariant_placeholder="".join(context_lines["violated_invariant"]) or "violated invariant — fill in from finding candidate",
                rule_lines=rules,
                exploit_lines=exploits,
                proof_plan_lines=proof_plans,
                role_lines=roles,
                setter_lines=setters,
                sink_lines=sinks,
                exploit_body_stub=exploit_body_stub,
            )
            invariant_body = GENERIC_INVARIANT_TEMPLATE.format(
                contract_name=args.contract_name,
                contest_lines=contest,
                privilege_lines=privilege,
                invariant_lines=invariant,
                violated_invariant_lines=violated_invariant_lines,
                violated_invariant_placeholder="".join(context_lines["violated_invariant"]) or "violated invariant — fill in from finding candidate",
                rule_lines=rules,
                exploit_lines=exploits,
                proof_plan_lines=proof_plans,
                role_lines=roles,
                setter_lines=setters,
                sink_lines=sinks,
            )
        else:
            # foundry (default)
            violated_invariant_lines = format_comment_block("violated invariant", context_lines["violated_invariant"])
            blocking_assumptions_lines = format_comment_block("blocking assumptions", context_lines["blocking_assumptions"])
            exploit_body = EXPLOIT_TEMPLATE.format(
                base_import=base_import,
                contract_name=args.contract_name,
                contract_path=contract_path,
                base_contract=base_contract,
                base_setup=base_setup,
                contest_lines=format_comment_block("contest", context_lines["contest"]),
                privilege_lines=format_comment_block("privilege", context_lines["privilege"]),
                invariant_lines=format_comment_block("invariant", context_lines["invariant"]),
                violated_invariant_lines=violated_invariant_lines,
                blocking_assumptions_lines=blocking_assumptions_lines,
                rule_lines=format_comment_block("rules", context_lines["rules"]),
                exploit_lines=format_comment_block("exploit families", context_lines["exploits"]),
                proof_plan_lines=format_comment_block("proof plan", context_lines["proof_plans"]),
                role_lines=format_comment_block("role constants", context_lines["roles"]),
                setter_lines=format_comment_block("candidate setters", context_lines["setters"]),
                sink_lines=format_comment_block("candidate sinks", context_lines["sinks"]),
                exploit_body_stub=exploit_body_stub,
            )
            invariant_body = INVARIANT_TEMPLATE.format(
                base_import=base_import,
                contract_name=args.contract_name,
                contract_path=contract_path,
                base_contract=base_contract,
                base_setup=base_setup,
                invariant_lines=format_comment_block("candidate invariant", context_lines["invariant"]),
                violated_invariant_lines=violated_invariant_lines,
            )

        write_text(exploit_path, exploit_body)
        write_text(invariant_path, invariant_body)

        # Post-generation TODO count — warn if scaffolding is still mostly placeholder
        exploit_todos = _count_remaining_todos(exploit_path)
        invariant_todos = _count_remaining_todos(invariant_path)

        if scaffold_family == "foundry":
            compile_check_passed, compile_warnings = run_compile_check(exploit_path, invariant_path)
        else:
            hardhat_bin = None
            toolchain = init_details.get("toolchain_config") or {}
            if isinstance(toolchain, dict):
                hardhat_bin = toolchain.get("binaries", {}).get("hardhat")
            compile_check_passed, compile_warnings = run_compile_check_generic(
                exploit_path, scaffold_family, hardhat_bin=hardhat_bin
            )
        warnings.extend(compile_warnings)

        template_note = {
            "foundry": "Foundry",
            "hardhat": "Hardhat",
            "generic": "generic Solidity",
        }.get(scaffold_family, scaffold_family)
        if compile_check_passed:
            knowledge_note = (
                f"Knowledge-grounded stubs generated from {vector_family} family."
                if vector_family and exploit_body_stub.strip()
                else "No matching vector knowledge found — agent must implement full exploit."
            )
            warnings.append(
                f"{template_note} scaffold created. "
                f"Exploit TODOs remaining: {exploit_todos} | Invariant TODOs: {invariant_todos}. "
                f"{knowledge_note}"
            )

        status = PhaseStatus(
            phase="scaffold_tests",
            ok=compile_check_passed,
            mode="full" if compile_check_passed else "degraded",
            artifacts={"exploit_test": str(exploit_path), "invariant_test": str(invariant_path)},
            warnings=warnings,
            errors=errors,
            details={
                "contract_name": args.contract_name,
                "contract_path": contract_path,
                "output_dir": args.output_dir,
                "force": args.force,
                "used_base_harness": bool(base_import) and scaffold_family == "foundry",
                "compile_check_passed": compile_check_passed,
                "run_id": run_id,
                "scaffold_family": scaffold_family,
                "vector_family": vector_family,
                "exploit_todos_remaining": exploit_todos,
                "invariant_todos_remaining": invariant_todos,
            },
        )
        return finalize(status)
    except ValueError as exc:
        status = make_failure_status("scaffold_tests", errors=[str(exc)], warnings=warnings)
        return finalize(status)
    except Exception as exc:
        status = fatal_status("scaffold_tests", exc, warnings=warnings)
        return finalize(status, exit_code=1)


if __name__ == "__main__":
    raise SystemExit(main())
